In [ ]:
# load necessary package
import numpy as np # load numpy as np
import pandas as pd # load pandas as pd

Pandas와 Numpay를 라이브러리를 import한다. (pd와 np로 불러올 수 있음)

# Data Type in Python

## Numberic Type

In [ ]:
n1=123
n2=1.4
n1+n2

124.4

## String Type

In [ ]:
s1="Kyunghee"
s2="University"
s1+s2

'KyungheeUniversity'

### String indexing (subsetting)

파이썬은 모든 숫자가 0부터 시작한다.(파이썬은 인덱스가 0부터 시작한다)

단, print[-3]의 경우처럼 뒤에서 부터 시작할 때에는 끝에서 1부터 시작한다.

In [ ]:
s="Kyunghee University"

In [ ]:
print(s[3]) # indexing the 4th character from the front (important: Python starts at the 0th element.)

n

In [ ]:
print(s[-3]) # indexing the 3rd character from the end

i

In [ ]:
print(s[0:4]) # indexing the 1st through 4th characters (for the number before : +1, for the number after :, as is)

Kyun

In [ ]:
print(s[1:2]) # indexing the 2nd through the 2nd characters--i.e., indexing the 2nd character

y

In [ ]:

print(s[4:]) # indexing everything from the 5th character

ghee University

## List Type

'a' is random can be anything  

내가 어떤 변수에 할당할 지는 자유!

In [ ]:
a=[1,2,3,4,5]

In [ ]:
print(a)

[1, 2, 3, 4, 5]

### List indexing

In [ ]:
print(a[0]) # indexing the 1st element from the front

1

In [ ]:
print(a[-1]) # indexing the 1st element from the end

5

In [ ]:
print(a[0:5]) # indexing the 1st through 5th elements (for the number before : +1, for the number after :, as is)

[1, 2, 3, 4, 5]

In [ ]:
print(a[:5]) # indexing everything through the 5th element

[1, 2, 3, 4, 5]

In [ ]:
print(a[2:]) # indexing everything from the 3rd element

[3, 4, 5]

In [ ]:
a[0]=11

### Adding, modifying, and removing elements in a list

In [ ]:
a.append(6) # add 6

append() 함수는 list 자료형과 짝꿍이다.  

보통 빈 리스트를 만든 후에 새로운 요소를 추가하는 방식으로 사용되며,  
for문에서 자주 등장한다.

In [ ]:
print(a)

[11, 2, 3, 4, 5, 6]

In [ ]:
a[0]=11 # change the 1st element to 11

In [ ]:
print(a)

[11, 2, 3, 4, 5, 6]

In [ ]:
del a[1] # remove the 2nd element

del은 인덱싱으로 요소를 삭제하는 방법이다.  

즉, 위치 기반 삭제! -> 0번째 위치 요소를 삭제해줘, 4번째 위치 요소를 삭제해줘 이런 식으로.. 

만약, 특정 '요소'로 지정하려면 .remove() 함수를 사용해야겠지

In [ ]:
print(a)

[11, 2, 3, 4, 5, 6]

1. del : 인덱스로 삭제  
> del은 함수가 아니라 예약어이다. 그렇기 때문에 함수와 같이 사용할 수 없다.

2. remove( ) 함수 : 값으로 삭제  
>remove 함수는 값으로 array의 요소를 삭제한다.`

### Merging and repeating lists

In [ ]:
a1=[1,2]

In [ ]:
a2=[3,4,5]

In [ ]:
a12=a1+a2 # merge

In [ ]:
print(a12)

[1, 2, 3, 4, 5]

In [ ]:
a3=a1*3 # repeat

In [ ]:
print(a3)

[1, 2, 1, 2, 1, 2]

## Python Statement

### if statement

In [ ]:
age = 19
if age < 20:
    print("You are a minor.")
elif age == 20:             # == - 같다!('='할당임)
    print("You just became an adult.")
else:
    print("You are an adult.")

You are a minor.

if의 조건문이 참일 때, 해당하는 코드를 실행한다.

거짓이면, else를 실행한다. (여기서 elif로 조건을 계속 걸어줄 수 있음. elif 여러번 올 수 있음)

In [ ]:
age = 20
if age < 20:
    print("You are a minor.")
elif age == 20:
    print("You just became an adult.")
else:
    print("You are an adult.")

You just became an adult.

In [ ]:
age = 21
if age < 20:
    print("You are a minor.")
elif age == 20:
    print("You just became an adult.")
else:
    print("You are an adult.")

You are an adult.

### for loop

In [ ]:
# The loop contiutes to print each item in the list UNTIL the last one, which is Univ.
list=["Kyung","Hee","Univ"]
for s in list:
    print(s)

Kyung
Hee
Univ

for문은 while문과 다르다!  
> while문과 반복 또는 순회라는 특징이 있지만, 중요한 것은 for loop는 '각 요소'에 대해 순회하는 것이다. (while이 전체 반복이라면!)  
> 다시말해, 요소를 하나씩 꺼내서 순회하면서 돌리는 것이 for loop이다.

In [ ]:
# range(5) generates the sequence of numbers from 0 to 4.
# Then, the loop continues to print each number in the sequence until the last one, which is 4.
for i in range(5):
    print(i)

0
1
2
3
4

In [ ]:
# range(4) generates the sequence of numbers from 0 to 3 for i.
# Then, the loop continues to add i to sum UNTIL the last element of i, which is 3 (0, 0+1, 1+2, 3+3).
sum=0
for i in range(4):
    sum=sum+i
print(sum)

6

### while loop

In [ ]:
# print i, while continuing to add 1 to i AS LONG AS it is smaller than 10.
i=0
while i<10:
    i=i+1
    print(i)

1
2
3
4
5
6
7
8
9
10

# NumPy Library

계산에 많이 쓰임(사회과학에서 대표적인 라이브러리 중 하나)

In [ ]:
pip install numpy # install numpy, but colab already has numpy installed

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import numpy as np # import numpy as np

In [ ]:
v=np.array([1,2,3,4]) # array command in np (numpy) library
print(v)

[1 2 3 4]

In [ ]:
v1=np.arange(12) # generate 12 numbers
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

## Pandas Library

df 관련 라이브러리

In [ ]:
pip install pandas # pandas already installed in colab

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### converting dictionary into series

In [ ]:
import pandas as pd # import pandas as pd

In [ ]:
dict_data={'a':1,'b':2,'c':3} # generate a dictionary with {key:value}

In [ ]:
print(type(dict_data)) # verify the class of data

<class 'dict'>

In [ ]:
print(dict_data) # check objects stored in dict_data

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
sr=pd.Series(dict_data) # convert dictionary into series

In [ ]:
print(type(sr)) # verify the class of data
# 데이터의 type가 dict이 아닌 시리즈가 된 것을 확인할 수 있다!

<class 'pandas.core.series.Series'>

In [ ]:
print(sr) #  check objects stored in sr

a    1
b    2
c    3
dtype: int64

### converting list into series

In [ ]:
list_data=['2023.01.01',3.14,'KBS',100] # generate a list

In [ ]:
print(list_data)

['2023.01.01', 3.14, 'KBS', 100]

In [ ]:
sr=pd.Series(list_data) # convert list into series

In [ ]:
print(sr) # List -> Series conversion automatically creates integer index

0    2023.01.01
1          3.14
2           KBS
3           100
dtype: object

## dataframe

In [ ]:
# Create multiple Series
series1 = pd.Series([1987,1992,1997,2002,2007,2012,2017,2022,2025])
series2 = pd.Series(["TW Roh","YS Kim","DJ Kim","MH Roh","MB Lee","GH Park","JI Moon","SY Yoon","JM Lee"])
series3 = pd.Series([89.2, 81.9, 80.7, 70.8, 63.0, 75.8, 77.2,77.1,79.4])
# Combine Series into a DataFrame
df = pd.DataFrame({'year': series1, 'president': series2,'rate':series3}) # column name
print(df)

   year president  rate
0  1987    TW Roh  89.2
1  1992    YS Kim  81.9
2  1997    DJ Kim  80.7
3  2002    MH Roh  70.8
4  2007    MB Lee  63.0
5  2012   GH Park  75.8
6  2017   JI Moon  77.2
7  2022   SY Yoon  77.1
8  2025    JM Lee  79.4

# load necessary package
import numpy as np # load numpy as np
import pandas as pd # load pandas as pd

교수님께서 제공해주신 'PEW.csv' 파일을 로드하여 실습해보자.

In [ ]:
print(pew) # use the print function to display data in a pandas dataframe
# 데이터프레임의 전반적인 모습을 볼 수 있다.

      psraid  sample  lang   FIPS  state  cregion usr  form  sex  q1  ...  \
0     100003       1     1  26081     26        2   S     2    1   3  ...
1     100007       1     1  26163     26        2   S     2    2   4  ...
2     100010       1     1  36051     36        1   S     2    2   3  ...
3     100012       1     1  12015     12        3   U     2    2   4  ...
4     100016       1     1  36119     36        1   S     2    2   1  ...
...      ...     ...   ...    ...    ...      ...  ..   ...  ...  ..  ...
2248  203938       2     1  48201     48        3   U     2    1   3  ...
2249  203946       2     1  28059     28        3   S     1    1   3  ...
2250  203948       2     1  48453     48        3   U     2    2   2  ...
2251  203950       2     1  48479     48        3   U     2    2   2  ...
2252  203956       2     1  55009     55        2   S     1    2   2  ...

     hisp race birth_hisp party  partyln  ideo inc i_user    weight   standwt
0       2    1                1              2  99      0  2.750000  0.942652
1       2    1                2              4   2      0  1.000000  0.342783
2       2    1                1              2   4      1  5.214286  1.787366
3       2    1                1              2   2      1  1.071429  0.367267
4       2    1                9        9     4  99      0  2.285714  0.783503
...   ...  ...        ...   ...      ...   ...  ..    ...       ...       ...
2248    1    6          1     2              3   6      1  4.750000  1.628217
2249    2    1                1              2   7      1  3.642857  1.248708
2250    2    1                3        1     2   6      1  6.500000  2.228087
2251    1    1          1     3        1     3   2      1  1.892857  0.648838
2252    2    1                4        8     9   8      1  2.500000  0.856956

[2253 rows x 122 columns]

In [ ]:
pew.head() # show the first first five rows
# ()에 인자로 10을 넣으면 상위 10개가 나온다. (내가 보고싶은 만큼 쓸 수 있음!)

,psraid,sample,lang,FIPS,state,cregion,usr,form,sex,q1,...,hisp,race,birth_hisp,party,partyln,ideo,inc,i_user,weight,standwt
0,100003,1,1,26081,26,2,S,2,1,3,...,2,1,,1,,2,99,0,2.750000,0.942652
1,100007,1,1,26163,26,2,S,2,2,4,...,2,1,,2,,4,2,0,1.000000,0.342783
2,100010,1,1,36051,36,1,S,2,2,3,...,2,1,,1,,2,4,1,5.214286,1.787366
3,100012,1,1,12015,12,3,U,2,2,4,...,2,1,,1,,2,2,1,1.071429,0.367267
4,100016,1,1,36119,36,1,S,2,2,1,...,2,1,,9,9,4,99,0,2.285714,0.783503

In [ ]:
pew.tail() # show the last first five rows
# 마찬가지로 인자 넣을 수 있음

,psraid,sample,lang,FIPS,state,cregion,usr,form,sex,q1,...,hisp,race,birth_hisp,party,partyln,ideo,inc,i_user,weight,standwt
2248,203938,2,1,48201,48,3,U,2,1,3,...,1,6,1,2,,3,6,1,4.750000,1.628217
2249,203946,2,1,28059,28,3,S,1,1,3,...,2,1,,1,,2,7,1,3.642857,1.248708
2250,203948,2,1,48453,48,3,U,2,2,2,...,2,1,,3,1,2,6,1,6.500000,2.228087
2251,203950,2,1,48479,48,3,U,2,2,2,...,1,1,1,3,1,3,2,1,1.892857,0.648838
2252,203956,2,1,55009,55,2,S,1,2,2,...,2,1,,4,8,9,8,1,2.500000,0.856956

In [ ]:
pew.describe() # provide summary statistics

,psraid,sample,lang,FIPS,state,cregion,form,sex,q1,intuse,...,educ,emplnw,hisp,race,party,ideo,inc,i_user,weight,standwt
count,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,...,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000,2253.000000
mean,142468.658233,1.399911,1.050599,27457.100311,27.372392,2.727918,1.493564,1.547714,2.731913,1.256991,...,4.483356,2.561917,1.998225,1.589436,2.651576,3.580559,22.825122,0.767421,2.917301,1.000000
std,48590.016939,0.489989,0.219226,16349.889657,16.329105,1.008889,0.500070,0.497829,1.235588,0.509328,...,1.780672,1.555174,0.953630,1.535146,1.838203,2.136404,37.076544,0.422570,1.553099,0.532375
min,100003.000000,1.000000,1.000000,1003.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.342783
25%,102340.000000,1.000000,1.000000,12086.000000,12.000000,2.000000,1.000000,1.000000,2.000000,1.000000,...,3.000000,1.000000,2.000000,1.000000,2.000000,2.000000,3.000000,1.000000,1.642857,0.563143
50%,104842.000000,1.000000,1.000000,27131.000000,27.000000,3.000000,1.000000,2.000000,3.000000,1.000000,...,5.000000,3.000000,2.000000,1.000000,2.000000,3.000000,6.000000,1.000000,2.500000,0.856956
75%,201503.000000,2.000000,1.000000,41071.000000,41.000000,4.000000,2.000000,2.000000,3.000000,1.000000,...,6.000000,3.000000,2.000000,1.000000,3.000000,4.000000,8.000000,1.000000,3.821429,1.309919
max,203956.000000,2.000000,2.000000,56039.000000,56.000000,4.000000,2.000000,2.000000,9.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,99.000000,1.000000,6.500000,2.228087

In [ ]:
pew.info() # give information about the datarame’s structure

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Columns: 122 entries, psraid to standwt
dtypes: float64(2), int64(26), object(94)
memory usage: 2.1+ MB

In [ ]:
# save rows 1 through 5 as pew_a dataframe (for the number before : +1, for the number after :, as is))
pew_a=pew[0:5]
print(pew_a) # in the result, row 0 is actually the 1st row and row 4 is actually the 5th row

   psraid  sample  lang   FIPS  state  cregion usr  form  sex  q1  ... hisp  \
0  100003       1     1  26081     26        2   S     2    1   3  ...    2
1  100007       1     1  26163     26        2   S     2    2   4  ...    2
2  100010       1     1  36051     36        1   S     2    2   3  ...    2
3  100012       1     1  12015     12        3   U     2    2   4  ...    2
4  100016       1     1  36119     36        1   S     2    2   1  ...    2

  race birth_hisp party  partyln  ideo inc i_user    weight   standwt
0    1                1              2  99      0  2.750000  0.942652
1    1                2              4   2      0  1.000000  0.342783
2    1                1              2   4      1  5.214286  1.787366
3    1                1              2   2      1  1.071429  0.367267
4    1                9        9     4  99      0  2.285714  0.783503

[5 rows x 122 columns]

In [ ]:
# save rows from the first through 3rd rows as pew_b dataframe
pew_b=pew[:3]
print(pew_b) # in the result, row 0 is actually the first row and row 2 is actually the 3rd row

   psraid  sample  lang   FIPS  state  cregion usr  form  sex  q1  ... hisp  \
0  100003       1     1  26081     26        2   S     2    1   3  ...    2
1  100007       1     1  26163     26        2   S     2    2   4  ...    2
2  100010       1     1  36051     36        1   S     2    2   3  ...    2

  race birth_hisp party  partyln  ideo inc i_user    weight   standwt
0    1                1              2  99      0  2.750000  0.942652
1    1                2              4   2      0  1.000000  0.342783
2    1                1              2   4      1  5.214286  1.787366

[3 rows x 122 columns]

In [ ]:
# save rows from the 2250th through the last rows as pew_c dataframe
pew_c=pew[2249:]
print(pew_c) # in the result, row 2249 is actually the 2250th row and row 2252 is the last row

      psraid  sample  lang   FIPS  state  cregion usr  form  sex  q1  ...  \
2249  203946       2     1  28059     28        3   S     1    1   3  ...
2250  203948       2     1  48453     48        3   U     2    2   2  ...
2251  203950       2     1  48479     48        3   U     2    2   2  ...
2252  203956       2     1  55009     55        2   S     1    2   2  ...

     hisp race birth_hisp party  partyln  ideo inc i_user    weight   standwt
2249    2    1                1              2   7      1  3.642857  1.248708
2250    2    1                3        1     2   6      1  6.500000  2.228087
2251    1    1          1     3        1     3   2      1  1.892857  0.648838
2252    2    1                4        8     9   8      1  2.500000  0.856956

[4 rows x 122 columns]

In [ ]:
# save'party' variable as pew_p dataframe
pew_p=pew['party']
print(pew_p)
pew.info()

0       1
1       2
2       1
3       1
4       9
       ..
2248    2
2249    1
2250    3
2251    3
2252    4
Name: party, Length: 2253, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Columns: 122 entries, psraid to standwt
dtypes: float64(2), int64(26), object(94)
memory usage: 2.1+ MB

In [ ]:
 # save the 1st, 2nd, 4th, and 11th columns as pew_d dataframe
pew_d=pew[pew.columns[[0,1,3,10]]]
print(pew_d)

      psraid  sample   FIPS  q2
0     100003       1  26081
1     100007       1  26163
2     100010       1  36051   0
3     100012       1  12015
4     100016       1  36119
...      ...     ...    ...  ..
2248  203938       2  48201   5
2249  203946       2  28059   0
2250  203948       2  48453  20
2251  203950       2  48479   2
2252  203956       2  55009  18

[2253 rows x 4 columns]

In [ ]:
# 'loc' indexes by index labels. in this case, indexes by column labels like ideo, weight
# save those as pew_iw dataframe
pew_iw=pew.loc[:,'ideo':'weight']
print(pew_iw)

      ideo  inc  i_user    weight
0        2   99       0  2.750000
1        4    2       0  1.000000
2        2    4       1  5.214286
3        2    2       1  1.071429
4        4   99       0  2.285714
...    ...  ...     ...       ...
2248     3    6       1  4.750000
2249     2    7       1  3.642857
2250     2    6       1  6.500000
2251     3    2       1  1.892857
2252     9    8       1  2.500000

[2253 rows x 4 columns]

In [ ]:
# extract only men (sex=1) and resave as pew_sex dataframe
pew_sex=pew[(pew['sex']==1)]
pew_sex.describe()

,psraid,sample,lang,FIPS,state,cregion,form,sex,q1,intuse,...,educ,emplnw,hisp,race,party,ideo,inc,i_user,weight,standwt
count,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000,1019.0,1019.000000,1019.000000,...,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000,1019.000000
mean,151431.739941,1.490677,1.060844,27812.389598,27.726202,2.731109,1.492640,1.0,2.790972,1.239450,...,4.446516,2.381747,1.997056,1.653582,2.633955,3.531894,19.942100,0.789009,3.142857,1.077317
std,49615.486518,0.500159,0.239161,16272.139283,16.252266,1.018649,0.500191,0.0,1.265562,0.487137,...,1.805861,1.582847,1.003428,1.606933,1.764768,2.110809,34.326864,0.408212,1.542003,0.528572
min,100003.000000,1.000000,1.000000,1003.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.342783
25%,102609.000000,1.000000,1.000000,12096.000000,12.000000,2.000000,1.000000,1.0,2.000000,1.000000,...,3.000000,1.000000,2.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.910714,0.654960
50%,105786.000000,1.000000,1.000000,28003.000000,28.000000,3.000000,1.000000,1.0,3.000000,1.000000,...,5.000000,2.000000,2.000000,1.000000,2.000000,3.000000,6.000000,1.000000,2.785714,0.954894
75%,201897.000000,2.000000,1.000000,42003.000000,42.000000,4.000000,2.000000,1.0,3.000000,1.000000,...,6.000000,3.000000,2.000000,2.000000,3.000000,4.000000,8.000000,1.000000,4.107143,1.407857
max,203946.000000,2.000000,2.000000,56039.000000,56.000000,4.000000,2.000000,1.0,9.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,99.000000,1.000000,6.500000,2.228087

In [ ]:
pew_sex=pew[(pew['sex']==2)]
pew_sex.describe()

,psraid,sample,lang,FIPS,state,cregion,form,sex,q1,intuse,...,educ,emplnw,hisp,race,party,ideo,inc,i_user,weight,standwt
count,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000,1234.0,1234.000000,1234.000000,...,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000,1234.000000
mean,135067.215559,1.324959,1.042139,27163.713128,27.080227,2.725284,1.494327,2.0,2.683144,1.271475,...,4.513776,2.710697,1.999190,1.536467,2.666126,3.620746,25.205835,0.749595,2.731043,0.936154
std,46460.078398,0.468550,0.200989,16414.607254,16.393109,1.001164,0.500171,0.0,1.208616,0.526704,...,1.759752,1.516527,0.910869,1.471784,1.897291,2.157337,39.055658,0.433422,1.538071,0.527224
min,100007.000000,1.000000,1.000000,1007.000000,1.000000,1.000000,1.000000,2.0,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.342783
25%,102164.250000,1.000000,1.000000,12073.000000,12.000000,2.000000,1.000000,2.0,2.000000,1.000000,...,3.000000,1.000000,2.000000,1.000000,2.000000,2.000000,3.000000,0.250000,1.500000,0.514174
50%,104285.000000,1.000000,1.000000,27053.000000,27.000000,3.000000,1.000000,2.0,3.000000,1.000000,...,5.000000,3.000000,2.000000,1.000000,2.000000,3.000000,6.000000,1.000000,2.285714,0.783503
75%,200877.750000,2.000000,1.000000,41047.000000,41.000000,4.000000,2.000000,2.0,3.000000,2.000000,...,6.000000,4.000000,2.000000,1.000000,3.000000,4.000000,9.000000,1.000000,3.598214,1.233405
max,203956.000000,2.000000,2.000000,56025.000000,56.000000,4.000000,2.000000,2.0,9.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,99.000000,1.000000,6.500000,2.228087

## Missing Values

In [ ]:
# q16 in pew (How often, if ever, do you talk about politics or current events with your family and friends?
# 1. Very often; 2. Sometimes; 3. Rarely; 4. Never; 8. Don’t know; 9. Refused)
pew['q16'].value_counts() # 8 and 9 are missing values

q16
1    809
2    738
3    416
4    276
9      7
8      7
Name: count, dtype: int64

In [ ]:
pew['q16'].mean() # including 8 and 9 inflates mean value

np.float64(2.110963160230803)

In [ ]:
print(pew['q16'].mean()) # print() for cleaner presentation of results

2.110963160230803

In [ ]:
from numpy import nan # importing numpy's nan package for handling missing values

In [ ]:
pew['q16m']=pew['q16'] # create a new variable q16m from q16 while copying all the values

In [ ]:
pew['q16m']=pew['q16m'].replace([8,9],nan) # modify 8 and 9 in q16m into nan (missing values) simultaneously

pew['q16m']=pew['q16m'].replace(8,nan) # modify 8 and 9 in q16m into nan (missing values) indiviudally
pew['q16m']=pew['q16m'].replace(9,nan) # modify 8 and 9 in q16m into nan (missing values) indiviudally

In [ ]:
pew['q16m'].value_counts(dropna=False) # include missing values in frequency table via dropna=False

q16m
1.0    809
2.0    738
3.0    416
4.0    276
NaN     14
Name: count, dtype: int64

In [ ]:
pew['q16m'].mean() # NaN will be excluded from mean; since 8 and 9 are exlcued, mean has become smaller

np.float64(2.071013845466726)

### saving data WITHOUT missing values

객체.dropna() -> 결측값을 버리는 코드이다.

In [ ]:
pew_filtered=pew.dropna() # save data WITHOUT missing values as a new object

In [ ]:
pew_filtered['q16m'].value_counts(dropna=False) # missing values are excluded from the new data

q16m
1.0    809
2.0    738
3.0    416
4.0    276
Name: count, dtype: int64

## Recoding

In [ ]:
# load necessary package
import numpy as np # load numpy as np
import pandas as pd # load pandas as pd

In [ ]:
# loading CSV file stored in google drive
# your own file path should be defined--i.e., where your file is stored in google drive
file_path='/content/drive/MyDrive/data analysis and coding/TESS.csv'
# save data as tess dataframe
tess=pd.read_csv(file_path)

In [ ]:
print(tess)

      CaseID  weight1  weight2    tm_start   tm_finish  duration  XTESS089  \
0          2     0.15     0.79  10/28/2011  10/28/2011         2        22
1          3     0.01     0.07  10/28/2011  10/28/2011         3        18
2          4     1.86     0.73  10/28/2011  10/28/2011         0         7
3          5     1.38     0.54  10/28/2011  10/28/2011         2        19
4          6     0.07     0.38  10/28/2011  10/28/2011         0        15
...      ...      ...      ...         ...         ...       ...       ...
2155    2206     0.22     0.37  11/15/2011  11/15/2011         3        13
2156    2207     1.63     2.76  11/15/2011  11/15/2011        14        20
2157    2208     0.12     0.20  11/15/2011  11/15/2011         2        24
2158    2209     0.04     0.22  11/15/2011  11/15/2011         2         3
2159    2210     1.76     2.98  11/15/2011  11/15/2011         1         4

      XPPRACEM  XPARTY7  XIDEO  ...  ppreg9 PPRENT  PPSTATEN  PPT01  PPT25  \
0            4        6      2  ...       1      1        14      0      0
1            4        5      3  ...       3      1        32      0      0
2            1        6      4  ...       2      1        22      0      0
3            1        5      4  ...       1      1        14      0      0
4            4        5      4  ...       8      1        86      0      0
...        ...      ...    ...  ...     ...    ...       ...    ...    ...
2155         5        6      4  ...       9      2        93      0      0
2156         1        7      4  ...       9      1        93      0      0
2157         7        6      1  ...       5      1        59      0      0
2158         4        5      3  ...       3      1        33      0      1
2159         1        3      4  ...       9      2        93      0      0

      PPT612  PPT1317  PPT18OV  PPWORK  PPNET
0          2        2        2       7      1
1          0        0        2       1      1
2          0        0        2       1      1
3          1        1        2       7      1
4          1        0        3       1      1
...      ...      ...      ...     ...    ...
2155       1        0        3       4      0
2156       0        0        2       5      0
2157       0        0        1       1      1
2158       0        0        3       1      1
2159       2        0        2       6      1

[2160 rows x 49 columns]

In [ ]:
tess['XREL1'].value_counts().sort_index(ascending=True) # frequency of values in ascending order

XREL1
-1       7
 1     415
 2     266
 3     535
 4      22
 5      23
 6      26
 7      67
 8      70
 9      73
 10      3
 11    254
 12     36
 13    363
Name: count, dtype: int64

### recoding into a new variable

In [ ]:
# defining recoding function
def rel_groups(series):
    if series == 3:
        return 100 # assign 100 to “3=Catholic”
    elif series == 1 or series == 2 or series == 4 or series == 9:
        return 200 # assign 200 to “1, 2, 4, 9=Protestant”
    elif series == 10 or series == 11:
        return 300 # assign 300 to “10, 11=Other.Christian”
    elif series == 13:
        return 400 # assign 400 to “13=Atheist”
    elif series == 5 or series == 6 or series == 7 or series == 8 or series == 12:
        return 500 # assign 500 to “5, 6, 7, 8, 12=Misc.Religion”
    elif series == -1:
        return np.nan # np.nan allows you to handle missing values

In [ ]:
# apply the defined recoding function to XREL1 and save it as religion5
tess['religion5']=tess['XREL1'].apply(rel_groups)

In [ ]:
# show frequency of religion5 including missing values in ascending order
tess['religion5'].value_counts(dropna=False).sort_index(ascending=True)

religion5
100.0    535
200.0    776
300.0    257
400.0    363
500.0    222
NaN        7
Name: count, dtype: int64

### recoding a numeric variable into a character variable

In [ ]:
 # create a new variable religion5.text from religion5 while copying all the values
tess['religion5.text']=tess['religion5']

In [ ]:
# recode numeric values into characters
tess['religion5.text']=tess['religion5.text'].replace([100,200,300,400,500],['Catholic','Protestant','Other Christian','Atheist','Misc Religion'])

In [ ]:
tess['religion5.text'].value_counts(dropna=False).sort_values(ascending=True) # 항목 빈도수로 정렬

religion5.text
NaN                  7
Misc Religion      222
Other Christian    257
Atheist            363
Catholic           535
Protestant         776
Name: count, dtype: int64

In [ ]:
# crosstab between recoded string variable (religion5.text in row) and original variable (XREL1 in column)
pd.crosstab(tess['religion5.text'],tess['XREL1'])

XREL1             1    2    3   4   5   6   7   8   9   10   11  12   13
religion5.text
Atheist            0    0    0   0   0   0   0   0   0   0    0   0  363
Catholic           0    0  535   0   0   0   0   0   0   0    0   0    0
Misc Religion      0    0    0   0  23  26  67  70   0   0    0  36    0
Other Christian    0    0    0   0   0   0   0   0   0   3  254   0    0
Protestant       415  266    0  22   0   0   0   0  73   0    0   0    0

# excersie

In [ ]:
# Create multiple series
series1 = pd.Series(["male","female","female","male","male","male","female"])
series2 = pd.Series([54, 34, 556, 57, 88, 856, 23])
# Combine series into a DataFrame
data = pd.DataFrame({'gender': series1, 'salary': series2}) # column name
print(data)

   gender  salary
0    male      54
1  female      34
2  female     556
3    male      57
4    male      88
5    male     856
6  female      23

In [ ]:
data['salary'].mean() # including 556 and 856 inflates mean value

np.float64(238.28571428571428)

In [ ]:
# define the function to recode values above 500 to nan
def recode_salary(value):
    if value > 500:
        return np.nan # recode values above 500 into missing values
    else:
        return value # copy all the other values

In [ ]:
# apply the function to the 'salary' column
data['salary'] = data['salary'].apply(recode_salary)

In [ ]:
data['salary'].value_counts(dropna=False).sort_index(ascending=True) # frequency showing missing value as NaN

salary
23.0    1
34.0    1
54.0    1
57.0    1
88.0    1
NaN     2
Name: count, dtype: int64

In [ ]:
data['salary'].mean() # 556 and 856 are now treated as missing values

np.float64(51.2)

### saving data WITHOUT missing values

In [ ]:
data_filtered=data.dropna() # save data WITHOUT missing values as a new object

In [ ]:
data_filtered['salary'].value_counts(dropna=False).sort_index(ascending=True) # frequency showing missing value as NaN

salary
23.0    1
34.0    1
54.0    1
57.0    1
88.0    1
Name: count, dtype: int64

In [ ]:
data_filtered['salary'].mean()

np.float64(51.2)

### replacing missing values with mean

In [ ]:
# you can also replace missing values with the mean of the other values
data['salary'] = data['salary'].replace(np.nan, np.mean(data['salary']))

In [ ]:
print(data)

   gender  salary
0    male    54.0
1  female    34.0
2  female    51.2
3    male    57.0
4    male    88.0
5    male    51.2
6  female    23.0