---
# Introduction to Python for Data Analysis (Study Notes)

*본 글은 경희대학교 미디어학과의 데이터분석과 코딩(이훈 교수님) 교과목의 강의 노트입니다* 
*강의자료를 바탕으로 강의 시간에 직접 필기하고 실습하며 이해한 내용을 재구성하였습니다*

---
## 수업 필기


Python은 데이터 분석에서 가장 널리 사용되는 언어 중 하나이다.  
데이터를 구조화하고, 계산하고, 분석하는 전 과정에서 Python은 높은 유연성을 제공한다.  
이 글에서는 Python 데이터 분석의 기초가 되는 핵심 개념과 문법을 정리한다.

### Numeric Type (숫자형 데이터)

Python의 숫자형 데이터는 대표적으로 `int`와 `float`가 있다.  
정수와 실수는 별도의 선언 없이도 자연스럽게 연산된다.

```python
a = 10        # int
b = 3.14      # float
```

a + b
a * b
연산 과정에서 정수와 실수가 함께 사용되면 결과는 자동으로 실수형으로 변환된다.


### String Type (문자열)
문자열은 텍스트 데이터를 다루는 기본 자료형이다.

text = "Data Analysis"
문자열은 인덱스를 통해 개별 문자에 접근할 수 있으며,
Python의 인덱스는 0부터 시작한다.

```python
text[0]     # 'D'
text[1]     # 'a'
text[-1]    # 's'
```

### List Type (리스트)
리스트는 여러 개의 값을 하나의 객체로 저장할 수 있는 자료형이다.
데이터 분석에서 가장 자주 사용되는 구조 중 하나이다.

numbers = [1, 2, 3, 4, 5]
리스트는 인덱싱뿐 아니라 요소의 추가, 수정, 삭제가 가능하다.

```python
numbers.append(6)     # 요소 추가
numbers[0] = 10       # 요소 수정
numbers.remove(3)     # 요소 삭제
```

### Tuple Type (튜플)
튜플은 리스트와 유사하지만 값을 변경할 수 없는 자료형이다.
변경되면 안 되는 값이나 설정값을 다룰 때 유용하다.

coords = (37.5, 127.0)


### Dictionary Type (딕셔너리)
딕셔너리는 key-value 구조를 가진 자료형이다.
구조화된 정보를 다룰 때 매우 유용하다.

```python
student = {
    "name": "Alice",
    "age": 23,
    "major": "Statistics"
}

student["name"]
student["age"]
```

### Set Type (집합)
집합(set)은 중복을 허용하지 않는 자료형이다.

```python
values = {1, 2, 2, 3}
values
```

중복 제거가 필요할 때 유용하게 활용할 수 있다.


### 조건문 (if / elif / else)  
조건문은 조건에 따라 다른 결과를 수행할 때 사용한다.

```python
score = 85

if score >= 90:
    result = "A"
elif score >= 80:
    result = "B"
else:
    result = "C"
```


### 반복문 (for / while)
반복문은 동일한 작업을 여러 번 수행할 때 사용된다.
데이터 전처리 과정에서 필수적인 문법이다.

```python
for i in range(5):
    print(i)
count = 0
while count < 5:
    print(count)
    count += 1
```

### 함수 (Function)
함수는 반복되는 작업을 정리하고 코드의 재사용성을 높여준다.

```python
def add(x, y):
    return x + y

add(3, 5)
```

분석 과정이 복잡해질수록 함수의 중요성은 더욱 커진다.

### NumPy 기초
NumPy는 수치 계산을 위한 핵심 라이브러리이다.

```python
import numpy as np

arr = np.array([1, 2, 3, 4])
arr.mean()
arr.sum()
```

NumPy를 활용하면 빠르고 효율적인 배열 연산이 가능하다.

### Pandas 기초
Pandas는 표 형태의 데이터를 다루는 데 특화된 라이브러리이다.
데이터 분석에서 가장 많이 사용되는 도구 중 하나이다.

```python
import pandas as pd

data = {
    "name": ["A", "B", "C"],
    "score": [90, 85, 88]
}

df = pd.DataFrame(data)
df
df["score"].mean()
```

Python 기본 데이터 타입

제어문과 함수

NumPy와 Pandas의 기본 구조

위 내용은 이후 통계 분석, 머신러닝, 데이터 시각화 학습으로 확장되는
모든 데이터 분석 작업의 기초가 된다.

### 그 외 메모들

#### String indexing (subsetting)

파이썬은 모든 숫자가 0부터 시작한다.(파이썬은 인덱스가 0부터 시작한다)

단, print[-3]의 경우처럼 뒤에서 부터 시작할 때에는 끝에서 1부터 시작한다.

In [ ]:
s="Kyunghee University"

In [ ]:
print(s[3]) # indexing the 4th character from the front (important: Python starts at the 0th element.)

n

In [ ]:
print(s[-3]) # indexing the 3rd character from the end

i

append() 함수는 list 자료형과 짝꿍이다.  

보통 빈 리스트를 만든 후에 새로운 요소를 추가하는 방식으로 사용되며,  
for문에서 자주 등장한다.

In [ ]:
del a[1] # remove the 2nd element

del은 인덱싱으로 요소를 삭제하는 방법이다.  

즉, 위치 기반 삭제! -> 0번째 위치 요소를 삭제해줘, 4번째 위치 요소를 삭제해줘 이런 식으로.. 

만약, 특정 '요소'로 지정하려면 .remove() 함수를 사용해야겠지

1. del : 인덱스로 삭제  
> del은 함수가 아니라 예약어이다. 그렇기 때문에 함수와 같이 사용할 수 없다.

2. remove( ) 함수 : 값으로 삭제  
>remove 함수는 값으로 array의 요소를 삭제한다.`

if의 조건문이 참일 때, 해당하는 코드를 실행한다.

거짓이면, else를 실행한다. (여기서 elif로 조건을 계속 걸어줄 수 있음. elif 여러번 올 수 있음)

for문은 while문과 다르다!  
> while문과 반복 또는 순회라는 특징이 있지만, 중요한 것은 for loop는 '각 요소'에 대해 순회하는 것이다. (while이 전체 반복이라면!)  
> 다시말해, 요소를 하나씩 꺼내서 순회하면서 돌리는 것이 for loop이다.

---

## excersie

교수님께서 제공해주신 코드로 실습을 해보자.

*실습을 위해 Pandas, Numpy 라이브러리를 load하였다*

In [ ]:
# Create multiple series
series1 = pd.Series(["male","female","female","male","male","male","female"])
series2 = pd.Series([54, 34, 556, 57, 88, 856, 23])
# Combine series into a DataFrame
data = pd.DataFrame({'gender': series1, 'salary': series2}) # column name
print(data)

   gender  salary
0    male      54
1  female      34
2  female     556
3    male      57
4    male      88
5    male     856
6  female      23

In [ ]:
data['salary'].mean() # including 556 and 856 inflates mean value

np.float64(238.28571428571428)

In [ ]:
# define the function to recode values above 500 to nan
def recode_salary(value):
    if value > 500:
        return np.nan # recode values above 500 into missing values
    else:
        return value # copy all the other values

In [ ]:
# apply the function to the 'salary' column
data['salary'] = data['salary'].apply(recode_salary)

In [ ]:
data['salary'].value_counts(dropna=False).sort_index(ascending=True) # frequency showing missing value as NaN

salary
23.0    1
34.0    1
54.0    1
57.0    1
88.0    1
NaN     2
Name: count, dtype: int64

In [ ]:
data['salary'].mean() # 556 and 856 are now treated as missing values

np.float64(51.2)

### saving data WITHOUT missing values

In [ ]:
data_filtered=data.dropna() # save data WITHOUT missing values as a new object

In [ ]:
data_filtered['salary'].value_counts(dropna=False).sort_index(ascending=True) # frequency showing missing value as NaN

salary
23.0    1
34.0    1
54.0    1
57.0    1
88.0    1
Name: count, dtype: int64

In [ ]:
data_filtered['salary'].mean()

np.float64(51.2)

### replacing missing values with mean

In [ ]:
# you can also replace missing values with the mean of the other values
data['salary'] = data['salary'].replace(np.nan, np.mean(data['salary']))

In [ ]:
print(data)

   gender  salary
0    male    54.0
1  female    34.0
2  female    51.2
3    male    57.0
4    male    88.0
5    male    51.2
6  female    23.0