문제 1) while loop / break 응용

1부터 어떤 수까지 차례대로 더할 때, 그 합이 5000을 처음으로 초과하는 순간의 숫자를 구하고자 한다.

그 숫자를 [inum]
그때까지의 누적합을 [isum]

이라는 이름으로 저장하시오.
단, isum은 반드시 5000을 초과한 값이어야 한다.

In [6]:
inum = 0
isum = 0

while isum <= 5000 : 
    inum = inum + 1
    isum = isum + inum
print(isum, inum)

5050 100

문제 2) 조건이 있는 for loop

1부터 100까지의 숫자 중에서, 30 이상 40 이하의 숫자는 제외하고 모두 더한 값을 구하시오.

결과를 [res] 라는 이름으로 저장하시오.

단, 반복문 안에서 조건문을 사용하시오.

In [10]:
res = 0
for x in range(1,101):
    if (x >= 30) and (x <= 40):
        continue 
    res += x
print(res, x)

4665 100

문제 3) dataframe 생성과 merge

다음 두 표를 각각 pandas dataframe으로 만드시오.

In [11]:
import pandas as pd

In [ ]:
dtA = pd.DataFrame({'id':[1,2,3],'socre2024':[80,75,90]})
dtB = pd.DataFrame({'id':[1,3,4],'socre2025':[85,95,70]})
print(dtA)
print(dtB)

   id  socre2024
0   1         80
1   2         75
2   3         90
   id  socre2025
0   1         85
1   3         95
2   4         70

In [19]:
# merge 해보자

dt_inner = pd.merge(dtA,dtB, on = 'id', how ='inner')
print(dt_inner)

dt_left = pd.merge(dtA, dtB, on = 'id', how = 'left')
print(dt_left)

dt_right = pd.merge(dtA, dtB, on = 'id', how = 'right')
print(dt_right)

dt_outer = pd.merge(dtA, dtB, on = 'id' , how = 'outer')
print(dt_outer)

   id  socre2024  socre2025
0   1         80         85
1   3         90         95
   id  socre2024  socre2025
0   1         80       85.0
1   2         75        NaN
2   3         90       95.0
   id  socre2024  socre2025
0   1       80.0         85
1   3       90.0         95
2   4        NaN         70
   id  socre2024  socre2025
0   1       80.0       85.0
1   2       75.0        NaN
2   3       90.0       95.0
3   4        NaN       70.0

문제 5) wide-form을 long-form으로 변환

다음 표를 [wdt1] 이라는 이름의 pandas dataframe으로 만드시오.

In [93]:
wdt1 = pd.DataFrame({'id': [1,2,3],'wage_2021':[10,20,15],'wage_2022': [12,18,17]})

In [94]:
wdt1

   id  wage_2021  wage_2022
0   1         10         12
1   2         20         18
2   3         15         17

**[wdt1]**를 reshape하여 long-form으로 만들되,
2021과 2022의 값은 year라는 변수로 만드시오.

long-form을 id 변수, year 변수 순서대로, 작은 값이 위로 오게(ascending) sort하여
**[ldt1]**이라는 이름으로 저장하시오.

**[ldt1]**의 1-3열은 id, year, wage 순서대로 있어야 합니다.

In [97]:
ldt1 = pd.wide_to_long(wdt1,['wage'],i='id',j='year',sep='_')
ldt1

         wage
id year
1  2021    10
2  2021    20
3  2021    15
1  2022    12
2  2022    18
3  2022    17

In [98]:
ldt1.columns

Index(['wage'], dtype='object')

In [99]:
ldt1 = ldt1.reset_index()

In [100]:
ldt1

   id  year  wage
0   1  2021    10
1   2  2021    20
2   3  2021    15
3   1  2022    12
4   2  2022    18
5   3  2022    17

In [101]:
ldt1.sort_values(by = ['id','year'],inplace= True)

In [104]:
ldt1 = ldt1.reset_index().drop('index',axis= 1)
ldt1

   id  year  wage
0   1  2021    10
1   1  2022    12
2   2  2021    20
3   2  2022    18
4   3  2021    15
5   3  2022    17

문제 6) long-form을 wide-form으로 변환

다음 표를 [ldt4] 라는 이름의 pandas dataframe으로 만드시오. 첫 번째 행은 변수명입니다.

In [105]:
ldt4 = pd.DataFrame({'pid':[1,1,2,2,3,3], 'year':[2021,2022,2021,2022,2021,2022],'score':[80,85,75,78,90,88]})
ldt4

   pid  year  score
0    1  2021     80
1    1  2022     85
2    2  2021     75
3    2  2022     78
4    3  2021     90
5    3  2022     88

**[ldt4]**를 reshape하여 wide-form으로 만들고,
결과를 **[wdt4]**라는 이름으로 저장하시오.

최종 결과는 각 사례가 한 행이 되도록 하며,
변수명은 pid, score2021, score2022 순서가 되도록 하시오.

In [116]:
wdt4 = pd.pivot(ldt4, index = 'pid',columns = 'year')
wdt4

     score
year  2021 2022
pid
1       80   85
2       75   78
3       90   88

In [117]:
wdt4 = wdt4.reset_index()

In [118]:
wdt4.columns = [f'{a}{b}' for a,b in wdt4.columns]
wdt4

   pid  score2021  score2022
0    1         80         85
1    2         75         78
2    3         90         88